apiVersion: v1
kind: Service
metadata:
  name: breaddispatcher
  labels:
    app: breaddispatcher
    component: frontend
    domain: prod
spec:
  ports:
  - port: 7080
    targetPort: 7080
    protocol: TCP
    name: client
  selector:
    app: breaddispatcher
    component: frontend
    domain: prod
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: breaddispatcher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: breaddispatcher
        component: frontend
        domain: prod
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "7080"
    spec:
      containers:
      - name: breaddispatcher
        image: gcr.io/myproj/breaddispatcher:v0.3.24
        ports:
        - containerPort: 7080
        args: [
          "-etcd=etcd:2379",
          "-event-server=events:7788",
        ]
